---
title: 'Buidling Blocks: Understanding Market Functionality'
author: "Earl Carlisle"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
  word_document: default
biblio-style: apsr
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
keywords: null
bibliography: ./master.bib
spacing: double
---


1. Read the paper _What Should Economists Do?_ by James M. Buchanan. 
  - Outline what Buchanan's main point is.
  - What does Buchanan mean by the word ___catallatics___?
  - According to Buchanan what do most economists do?
  - What does he think they should do differently?

# *Answer to 1*

Buchanan's main point is that is that economists shouldn't focus on the simple idea of choice allocation. On page 214, he states "Only since ___The Nature and Significance of Economic Science___ @buchanan1964 should have economists so exclusively devoted their energies to the problems raised by scarcity, ..., and to the necessity for the making of allocative decisions." He thinks that economists should focus more of their time on working on catallactics. A quick Wikipedia search and you can get a rough idea of what this means. According to the article "Catallactics is a theory of the way the free market system reaches exchange ratios and prices.  It aims to analyze all actions based on monetary calculation and trace the formation of prices back to the point where an agent makes his or her choices. It explains prices as they are, rather than as they "should" be." This essentially means that the economists should not focus on their simplified equilibrium models, but instead, focus on the broader picture. Buchanan quotes Adam Smith as the foundation of markets, stating "is not originally the effects of any human wisdom, which foresees and intends that general opulence to which it gives occasion. It is the necessary, though very slow and gradual, consequence of a certain propensity in human nature which has in view no such extensive utility; the propensity to truck, barter, and exchange one thing for another." It's this last phrase that should be focused on. This is what markets are based on, as alluded by Buchanan. This is what he wants more economists to focus on. It's this market system that Buchanan refers to as catallactics. 

As I have alluded before hand, economists at this point in time focused way to much on this choice allocation theory. They used perfect equilibrium models to postulate how a market should be. They replace the individual with the society and only focus on that. They fail to understand that it's the individual, exercising their agency to better themselves, to establish the market under inspection. 

Buchanan believes that economists believe that should focus on other areas, and not hone in on this one specific area of their science. He insists that more focus be set on how individuals enter into contacts with each other. In other words, he believes that the idea of how market structures should be expanded and analyzed. The view of economics should be broadened to apply to all aspects of life. This is because almost all interactions can be viewed as economic interactions (with some mixture of political interaction). 

#*Actual Paper Start

# *Abstract*

The purpose of this paper is to aggregate, at least in part, some of the writings and criticisms of economists. Too many economists focus on simplified, perfect models. They either forget, or ignore what originally created these simplified markets. All of them, somehow, stemmed from humanities "propensity to truck, barter, and exchange one thing for another" @buchanan1964should(quoting Adam Smith). This paper pulls from several economic writings in order 'nudge' economists to return to their roots of examining markets in order understand, and postulate what makes them.

# *I*

This paper is an attempt, and a rather poor one at that, of aggregating some of the extensive knowledge of our economic predecessors. Drawing upon their extensive knowledge, a presentation will be made for why economists should examine the framework that creates their model. The idea that Buchanan (buchanan1964should) put forth is that economists should look at all interactions as a mix of political and economic. They should not simply be focused on the model, but they should examine what makes the model: daily interaction among individuals. It was this lack of examination that Buchanan criticized originally. This paper has the intent to continue on that noble work and help us all be better to understand our daily interaction, and how to better model it in our desire to further understand, and push, the bounds of human ability. As Buchanan stated "Learning more about how markets work means learning more about how markets work." @buchanan1964should

# *II*
Two of the most arguably most brilliant economist to ever walk this earth were Dr. F.A.Hayek and Dr. James Buchanan. They have authored many a work to push our society forward. A topic that they both have in common is the idea of choice and focusing on individual choices that make up the collective whole of a market. Both of these economic giants have written upon the idea that too much time is focused entirely upon simple equalibrium equations. To much time is being spent on simplified models that don't refer to how the market was that is being studied came about in the first place. 

In James Buchanan's piece, __What Should Economists Do?__ he gives us the opinion that to many economists are studying the concept of allocation resource problems. This issue was first proposed, according to Buchanan,by Lord Robbins in __The Nature and Significance of Economic Science__. Buchanan points the blame of this problem to Lord Robbins' ambiguity in the principal agent problem. According to Buchanan, to many economists have started to aggrigate individuals into groups of societies, and only dealing with said socities. This creates the problem in which it's much harder to see how a market forms, obscuring any sort of analysis that is gained when studying markets. To be fair, and Buchanan is fair, this issue is not all of Robbins fault. True, if had not remaied neutral things would be different. But the issue here, is that individuals are allowed to make choices. This makes it so that any economists has the opporturnity to extrapolate and build upon the framework given by Robbins. This means that they are able to make decisions and extrapolate on their own. It was later economists that chose to continue and further the aggrigation issue.  @buchanan1964should

Another issue, probably the more important issue, that Buchanan brings up in this same paper, is that once only worry about a society in the markplace, you start to only focus on maximazation problems. It appers, that once the initail concept of the market, in their eyes, is solidified, then mathematics is all that is necessary. To this, Buchanan stats "I am urging that they be recognized for what they are, contributions to applied mathematics, to managerial science if you will, but not to our chosen subject field whcich we, for better or for worse, call "economics."" 

Instead of all of this, Buchanan would have us focus on the idea of "catallactics" Catallactics, as defined by Wikipedia states "Catallactics is a theory of the way the free market system reaches exchange ratios and prices.  It aims to analyze all actions based on monetary calculation and trace the formation of prices back to the point where an agent makes his or her choices. It explains prices as they are, rather than as they "should" be." The reason why this is important, is because it deals with the conception of the market, it's growth and life span, not simply performing an analysis ona full formed market. This is important because it examines the very foundation of of a life form, not on how the life form should have evolved, but how it did. As Buchanan states in the same paper from above, "Man's behavior in the market relationship, reflecting the propensity to truck and to barter, and the manifold variations in structure that this relationship can take; these are the proper subjects for the economist's study." Essentially what he is saying, is exactly what this paper is saying, it's very important to look at the formulation and structure of the market. It's not enough to analyize a fully formed market, or even a fledgling one. It's just as important to understand the underlying mechanism of how the market came to be. Once the history has been established, it will give the economist a better idea of how to analyze the market, and to see which paramaters truly merit testing. Latter in this paper, Elinor Ostrom's book, __Governing the Commons__ will help to clarify this concept. @Catallactics2018 

In Section 4 of __The Collected Works of James M. Buchanan, Volume 1, The Logical FOundations of Constitutional Liberty__, the paper __Natural and Artifact Man__ gets more atomic on this concept of analyzing the formation of markets. The bulk of this paper deals with the concept of man and his ability to choose. Now, it does focus on the libery desired by man in order to make up his life, but that's not what this paper will focus on. This paper will, instead, take some of that argument to reinforce what Buchanan stated in __What Should Economists Do?__. @buchanan1999logical

The article does a great job of pointing out that utility functions, and by extention markets, fail to account for the passage of time. This time variable can be thought of in two different ways. One, and the most straight forward, is the concept of time itselt and how it moves. The other one, and possibly more important with the concept of the passage of time, is self realization. In comparing humans and Buchanans' dog, he states "As human beings, we know that we are going to die; perhaps my dog does not know this about himself. But we, as human beings, also know that we can, within limits, shape the form of being that we shall be between now and the time of death, even when we fully reckon on the stochastic patter of life expectancy." It's this concept of change that is most central to our discussion here. The ability for us to change is an important aspect in market creation and management. The concept that Buchanan address is that people's preferences change, if they were ever fully formed in the first place. He specifically uses the idea of a smoker stopping to smoke. Originally, the utility curve has smoking some where in there. But, over time, as the smoker decides to be a non-smoker, that utility curve has changed. Smoking is no longer a part of the demand of goods this individual has. His preferences have changed, and thus the market demand has decreased. The same could be said for any sort of change in ones preferences. This small detail shows, in fact, that no market is static. That as individuals make choices, markets will receive a reflection of theses changed preferences. It is the consumers, after all, that truly drive a market. @buchanan1999logical

We will now pivot to Hayek to obtain more insight on the issue of plug and play equalibrium/maximization economics. __The Pretence of Knowledge__ perfectly helps emphasize and reiterate what Buchanan has explaiend above. Hayek lays that economists have become to obsessed with being "scientistic". He defines this as "Is decidedly unscientific in the true sense of the word, since it involves a mechanical and uncritical application of habits of thought to fields different from those in which they have been formed." This is perfectly in line with which Buchanan outlied. The way that Hayek lays out this argument is by showing the differences between physical sciences and social sciences (of which Economics is one). His biggest quandry is that too many economists are focusing on being like physical sciences. He states, on page 6, that "The chief point we must remember is that the great and rapid advance of the physical sciences took place in fields where it proved that explanation and prediction could be based on laws which accounted for the observed phenomena as functions of comparatively few variables - either particular facts or relative frequencies of events." Essentially, what Hayek is trying to tell us is that the physical sciences came out of theories that are able to be replicate with exact information. He states over and over again that economists cannot obtain the exact information necessary to obtain these specific figures. He goes on to explain that "Yet the confidence in the unlimeted power of science is only too often based on a flase believe that the scientific method consists in the application of a ready-made technique, or in imitating the form rather than the substance of scientific procedure, as if one needed only to follow some cooking recipes to solve all social problems." @Hayek1989pretence

In this same article, Hayek goes on to explain the economists dilema of being "scientisic". He states that explains that we cannot know all of the parts that make up the certain out comes. As it were, we cannot know all of the ingredients and timing to achieve what physical science can. In other words "In the explanation of the working of such structures we can for this reason not replace the information aobut the individual elemetns by statistical information, but require full information about each element if from our theory we are to dervie specific preditions aobut individual events. Without such specicific information aobut the individual elements we shall be confined to what on another occasion I have called mere pattern predictions - predictions of some of the general attributes of the structures that will form themselves, but not containing specific statements about the individual elements of which the structures will be made up." Breaking this down, Hayek is saying that economists use a lot of statistical predictions to come to conclusions in their models. Statstics is not a perfect science for prediction, but a good notion of what could happen.  

This whole concept is further explored in Hayaks __The Use of Knowledge in Society__. This paper dissects the idea of centrally planned economy. He explains here that it is impossible to know all of the factors that go into production. That is why a dissentralized economy is better.One does not have to know everything in order to achieve good outcomes. Market forces, and those that make up the markets, will eventually lead to good allocation of scarce resources. This is what the above paper is trying to tell people. It is impossible to know all aspects of a market or an economy and what goes into them. It's impossible for someone to know how to "fix" an economy because they cannot know all the factors that make up said economy. @hayek1945use

#*III*

Now that this anti-plug and play framework has been set up, it's time to turn to some more examples of this. The best example, and probably most expansive and precise, is that of Elinor Ostroms book __Governing the Commons__. Now, this book is to great to try and flesh out in this short paper. But it can be best summarized as a way to to solve the Tragedy of the Commons. According to her book, most people try to solve this issue by either assigning property rights to individuals, or give governance to a central government. Ostroms whole point of the book is that there is a better way. She goes through several examples of what she calls Common Pool Resources and how they survive. We won't go to far into her explanations because, quite frankly, this paper cannot do it justice. One main point that we will briefly touch on is the importance of the individual. It is individuals that make up every aspect of these CPR's, both for success and for destruction of them. Individuals make up the watchers, the maintainers, as well as the organizers. It is the decions of the individuals that make up everything. She stresses this througout the book. Without them, solving these issues would not possible. @ostrom2015governing

This goes back to the earlier discussion of how markets are made with what Buchanan stated in __What Should Economists Do?__ "Man's behavior in the market relationship, reflecting the propensity to truck and to barter, and the manifold variations in structure that this relationship can take;" His point is that it's the individual that makes up the market, just like it's the individual that makes up the CPR. This is why the study of the individual in context of the market is so important. It simply is not enough to just aggregate them into society and judge the market that way, as previous stated by Bucanan. @buchanan1964should

In their paper __What did Economists Do? Euvoluntary, VOluntary, and Coercive Instituions for Collective Action__, William Shughart and Diana Thomas explain what economists did do after Buchanan's plea. Most of what they did is similiar, if not exactly the same as Ostroms research. Essentially, at least in part, some economists have broken away from maximization and equilibrium equations. Instead, they have started to look at individuals and the social contracts that they can enter into to make up markets. These markets can be CPR's, as previous suggested, or other type of market structures, like club goods. Essentially what they did do is exactly what Buchanan asked them to do, to move away from plug and play ecomonics via applied mathematics. @shughart2014did


#*IV*

In conclusion, economists, at least some, took Buchanan's plea to move away from maximization functions and started digging into choices that individuals makes. These decisions of course made made ripples in the markets that these individuals participated in. Economics has come a long way since the initial plea made by Buchanan. Luckily for him, he had another voice in that same vain. That was Hayek, who also pleading the same message at the same time. Both of them, in unison, were asking that current economists change course to not turn their field of sceince into "applied mathematics", but to remain interesting, trying to solve interesting questions aobut the world around us. 

Economists have become more interesting as they changed course. They have started to open up more ideas in this wondrous field. Economists like Ostrom did exactly what these two other asked of her, and started looking at the market system. She focused specificially on CPR's, but over all made great strides to help all economists. She created a framework for analyzing these CPR's, as illustrated in her book, cited above. As illustrated in the Shughart and Thomas paper, other economists have followed suite in following the guidence of Buchanan and Hayek. 

Econonmists have started to do a better job at analyzing the individuals that make the market system in question. This is exactly what Buchanan and Hayek wished for. At least some have opted for more individual control, to be able shape markets in their own reflections, for what they wish to consume. It is a great mystery of where this great field would be without the guidence of such great masters. Overall, both Buchanan and Hayek have done a great service in saving our beloved branch of science, known as economics. 










ending on the idea that perhaps the idea of utility functions could be going out of style (@buchanan1964should page 217)

There is still value in using equilibrium models, it just shouldn't be the sole focus. 



# *References*


@article{Hayek1989pretence, title={The pretence of knowledge}, author={Hayek, Friedrich August}, journal={The American Economic Review}, volume={79}, number={6}, pages={3--7}, year={1989}, publisher={JSTOR} 
}

@article{buchanan1987constitution, title={The constitution of economic policy}, author={Buchanan, James M}, journal={The American economic review}, volume={77}, number={3}, pages={243--250}, year={1987}, publisher={JSTOR} 
}


@book{ostrom2015governing,
  title={Governing the commons},
  author={Ostrom, Elinor},
  year={2015},
  publisher={Cambridge university press}
}

@article{buchanan1964should, title={What should economists do?}, author={Buchanan, James M}, journal={Southern Economic Journal}, pages={213--222}, year={1964}, publisher={JSTOR} 
}

@misc{buchanan1999logical,
  title={The logical foundations of constitutional liberty: The collected works of James M},
  author={Buchanan, James M},
  year={1999},
  publisher={Buchanan}
}
  
@article{hayek1945use,
  title={The use of knowledge in society},
  author={Hayek, Friedrich August},
  journal={The American economic review},
  volume={35},
  number={4},
  pages={519--530},
  year={1945},
  publisher={JSTOR}
}

@article{shughart2014did,
  title={What did economists do? Euvoluntary, voluntary, and coercive institutions for collective action},
  author={Shughart, William F and Thomas, Diana W},
  journal={Southern Economic Journal},
  volume={80},
  number={4},
  pages={926--937},
  year={2014},
  publisher={Wiley Online Library}
}

@webarticle{Catallactics2018,
  title={Catallactics.},
  year = {2018},
  publisher = {Wikipedia}
  website = {https://en.wikipedia.org/wiki/Catallactics}
}


<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

